def stampa():
	tau,f,p=transpose(loadtxt("sim_vs_L.dat"))
	tau,f_teor,p_teor=transpose(loadtxt("UCNA_vs_L.dat"))
	plot(tau,f,"b.",tau,f_teor,"g-")
	legend(['simulation', 'UCNA'])
	xlabel("$\mathscr{L}$")
	ylabel("$<|F|>$")
	title("$<|F|>$ vs $\mathscr{L}$")
	semilogx()
	savefig("F_vs_L.pdf")
	figure()
	plot(tau,p,"b.",tau,p_teor,"g-")
	legend(['simulation', 'UCNA'])
	xlabel("$\mathscr{L}$")
	ylabel("$p$")
	semilogx()
	title("$p$ vs $\mathscr{L}$")
	savefig("p_vs_L.pdf")
