from os import*
D=0.1;tau=0.06;v=sqrt(D/tau)
def stampa():
	figure(0)
	b,h=np.load("./r=0.5/F.npy")
	plot(b,h/v)
	b,h=np.load("./r=0.3/F.npy")
	plot(b,h/v)
	b,h=np.load("./r=0.2/F.npy")
	plot(b,h/v)
	b,h=np.load("./r=0.05/F.npy")
	plot(b,h/v)
	b,h=np.load("./r=0.02/F.npy")
	plot(b,h/v)
	b,h=np.load("./point/F.npy")
	plot(b,h/v)
	legend(["$r=0.5$","$r=0.3$","$r=0.2$","$r=0.05$","$r=0.02$","point"],"best")
	figure(figsize(4,3))
	b,h=np.load("./r=0.5/F_cumulative.npy")
	plot(b,h/v)
	b,h=np.load("./r=0.3/F_cumulative.npy")
	plot(b,h/v)
	b,h=np.load("./r=0.2/F_cumulative.npy")
	plot(b,h/v)
	b,h=np.load("./r=0.05/F_cumulative.npy")
	plot(b,h/v)
	b,h=np.load("./r=0.02/F_cumulative.npy")
	plot(b,h/v)
	'''b,h=np.load("./point/F_cumulative.npy")
	plot(b,h/v)''' 
	plot(cos(pi/4),-2*D*(sqrt(D*tau)+1)*cos(pi/4)/v,"o",ms=7,mec="k",mew=2.,c="w",alpha=0.7)
	xlim(-1.1)
	ylim(-0.17)
	legend(["$r=0.5$","$r=0.3$","$r=0.2$","$r=0.05$","$r=0.02$"],loc=(0.15,0.32),frameon=False)
	ylabel("$\sum_{y'}^y F_y^' /\\left(v \\rho_{bulk}\\right)$",fontsize=8)
	xlabel("$y$",fontsize=8)
	tight_layout()
	ylabel("$\sum_{y'}^y F_{y'} /\\left(v \\rho_{bulk}\\right)$",fontsize=16)
	xlabel("$y$",fontsize=16)
	ax=gca()
	ax.yaxis.set_label_coords(-0.17,0.5)


