def stampa():
	tau,f,p=transpose(loadtxt("sim_vs_tau.dat"))
	tau,f_teor,p_teor=transpose(loadtxt("UCNA_vs_tau.dat"))
	plot(tau,f,"b.",tau,f_teor,"g-")
	legend(['simulation', 'UCNA'])
	xlabel("$\\tau$")
	ylabel("$<|F|>$")
	title("$<|F|>$ vs $\\tau$")
	semilogx()
	savefig("F_vs_tau.pdf")
	figure()
	plot(tau,p,"b.",tau,p_teor,"g-")
	legend(['simulation', 'UCNA'])
	xlabel("$\\tau$")
	ylabel("$p$")
	semilogx()
	title("$p$ vs $\\tau$")
	savefig("p_vs_tau.pdf")
