def stampa():
	L,f_pol,p_bordo_pol=transpose(loadtxt("./poligoni/D=1/sim_vs_L.dat"))
	tau,f_pol_4,p_bordo_pol_4=transpose(loadtxt("./poligoni/D=4/sim_vs_tau.dat"))
	t=linspace(-4,3,100)
	t=10**t
	#subplot(311)
	figure(figsize=[4,3])
	'''plot(t,pi/(2*pi*sqrt(t)*(1+sqrt(t))+pi),color="b",label="UCNA,$D=1$")
	plot(t,pi/(2*pi*sqrt(4*t)*(1+sqrt(4*t))+pi),color="magenta",label="UCNA,$D=4$")'''
	plot(t,pi/(2*pi*sqrt(t)*(1+sqrt(t))+pi),color="b")
	plot(t,pi/(2*pi*sqrt(4*t)*(1+sqrt(4*t))+pi),color="magenta")
	plot(L**2,(1-p_bordo_pol),"s",label="$D=1$",ms=5,mec="b",mew=2,c="w",alpha=0.7)
	plot(tau,(1-p_bordo_pol_4),"o",label="$D=4$",ms=5,mec="m",mew=2,c="w",alpha=0.7)
#	axvline(0.5,color="red",ms=3)
	legend(loc="best",numpoints=1)
	xlabel("$\\tau$",fontsize=8)	
	ylabel("$\\rho_{Bulk}$",fontsize=8)
	semilogx()
	tight_layout()
	xlabel("$\\tau$",fontsize=18)	
	ylabel("$\\rho_{Bulk}$",fontsize=18)
	l=linspace(-2,2,100)
	l=10**l
	figure(figsize=[4,3])
	#subplot(312)
	plot(L,(1-p_bordo_pol),"s",label="$D=1$",ms=5,mec="b",mew=2,c="w",alpha=0.7)
	plot(sqrt(tau*4),(1-p_bordo_pol_4),"o",label="$D=4$",ms=5,mec="m",mew=2,c="w",alpha=0.7)
	plot(l,pi/(2*pi*l*(1+l)+pi),color="k",label="UCNA")
	semilogx()
	legend(loc="best",numpoints=1)
	xlabel("$\\mathscr{L}/R$",fontsize=8)	
	ylabel("$\\rho_{Bulk}$",fontsize=8)
	tight_layout()
	xlabel("$\\mathscr{L}/R$",fontsize=18)	
	ylabel("$\\rho_{Bulk}$",fontsize=18)
	#subplot(313)
	figure(figsize=[4,3])
	plot(L,f_pol/(2*pi*1/pi),"s",label="$D=1$",ms=5,mec="b",mew=2,c="w",alpha=0.7)
	plot(sqrt(tau*4),f_pol_4/(2*pi*4/pi),"o",label="$D=4$",ms=5,mec="m",mew=2,c="w",alpha=0.7)
	plot(l,2*pi*(1+l)/(2*pi*l*(1+l)+pi)/(2*pi*1/pi),color="k",label="UCNA")
	xlabel("$\\mathscr{L}/R$",fontsize=8)	
	ylabel("$p/p_0$",fontsize=8)
	legend(loc="best",numpoints=1)
	semilogx()
	tight_layout()
	xlabel("$\\mathscr{L}/R$",fontsize=18)	
	ylabel("$p/p_0$",fontsize=18)

	figure(figsize=[4,3])
	plot(L,f_pol/(2*pi*1/pi),"s",label="$D=1$",ms=5,mec="b",mew=2,c="w",alpha=0.7)
	plot(sqrt(tau*4),f_pol_4/(2*pi*4/pi),"o",label="$D=4$",ms=5,mec="m",mew=2,c="w",alpha=0.7)
	plot(l,2*pi*(1+l)/(2*pi*l*(1+l)+pi)/(2*pi*1/pi),color="k",label="UCNA")
	plot(l,1/(2*l),"-.",label="$R/(2\\mathscr{L})$")
	plot(l,1/(sqrt(2)*l),"--",label="$R/(\\sqrt{2}\\mathscr{L})$")
	xlabel("$\\mathscr{L}/R$",fontsize=8)	
	ylabel("$p/p_0$",fontsize=8)
	legend(loc="best",frameon=False,numpoints=1,fontsize=14)
	loglog()
	ylim(0.015,1.3)
	tight_layout()
	xlabel("$\\mathscr{L}/R$",fontsize=18)
	ylabel("$p/p_0$",fontsize=18)
				
def circle_vs_polygon():
	figure(figsize=[4,3])
	L,f_cer,p_bordo_cer=transpose(loadtxt("./puro_cerchio/changing_L/sim_vs_L.dat"))
	L,f_pol,p_bordo_pol=transpose(loadtxt("./poligoni/D=1/sim_vs_L.dat"))
	plot(L**2,(1-p_bordo_cer),"o",label="Circle",ms=10,mec="m",mew=2,c="w",alpha=0.8)
	plot(L**2,(1-p_bordo_pol),"s",label="Polygon",ms=5,mec="b",mew=2,c="w",alpha=0.8)
	xlabel("$\\tau$")	
	ylabel("Bulk Density")
	legend(loc="best",numpoints=1)
	xlabel("$\\tau$",fontsize=13)
	ylabel("$\\rho_{Bulk}$",fontsize=13)

