from os import*
def stampa():
	figure(0)
	b,h=np.load("./r=0.5/F.npy")
	plot(b,h)
	b,h=np.load("./r=0.3/F.npy")
	plot(b,h)
	b,h=np.load("./r=0.2/F.npy")
	plot(b,h)
	b,h=np.load("./r=0.05/F.npy")
	plot(b,h)
	b,h=np.load("./r=0.02/F.npy")
	plot(b,h)
	b,h=np.load("./point/F.npy")
	plot(b,h)
	legend(["$r=0.5$","$r=0.3$","$r=0.2$","$r=0.05$","$r=0.02$","point"],"best")
	figure(1)
	b,h=np.load("./r=0.5/F_cumulative.npy")
	plot(b,h)
	b,h=np.load("./r=0.3/F_cumulative.npy")
	plot(b,h)
	b,h=np.load("./r=0.2/F_cumulative.npy")
	plot(b,h)
	b,h=np.load("./r=0.05/F_cumulative.npy")
	plot(b,h)
	b,h=np.load("./r=0.02/F_cumulative.npy")
	plot(b,h)
	b,h=np.load("./point/F_cumulative.npy")
	plot(b,h)
	legend(["$r=0.5$","$r=0.3$","$r=0.2$","$r=0.05$","$r=0.02$","point"],"best")

