def stampa():
	tau,f,p=transpose(loadtxt("sim_vs_D.dat"))
	tau,f_teor,p_teor=transpose(loadtxt("UCNA_vs_D.dat"))
	plot(tau,f,"b.",tau,f_teor,"g-")
	legend(['simulation', 'UCNA'])
	xlabel("$D$")
	ylabel("$<|F|>$")
	title("$<|F|>$ vs $D$")
	semilogx()
	savefig("F_vs_D.pdf")
	figure()
	plot(tau,p,"b.",tau,p_teor,"g-")
	legend(['simulation', 'UCNA'])
	xlabel("$D$")
	ylabel("$p$")
	semilogx()
	title("$p$ vs $D$")
	savefig("p_vs_D.pdf")
